/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ActivityType = IDL.Variant({
  'affirmation' : IDL.Null,
  'word_association' : IDL.Null,
  'journaling' : IDL.Null,
});
export const ResourceCategory = IDL.Variant({
  'book' : IDL.Null,
  'article' : IDL.Null,
  'podcast' : IDL.Null,
  'activity' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Type__2 = IDL.Variant({
  'affirmation' : IDL.Null,
  'word_association' : IDL.Null,
  'journaling' : IDL.Null,
});
export const LanguageActivity = IDL.Record({
  'id' : IDL.Nat,
  'difficultyLevel' : IDL.Nat,
  'title' : IDL.Text,
  'activityType' : Type__2,
  'prompt' : IDL.Text,
});
export const Type__1 = IDL.Variant({
  'book' : IDL.Null,
  'article' : IDL.Null,
  'podcast' : IDL.Null,
  'activity' : IDL.Null,
});
export const WellnessResource = IDL.Record({
  'id' : IDL.Nat,
  'url' : IDL.Text,
  'title' : IDL.Text,
  'tags' : IDL.Vec(IDL.Text),
  'description' : IDL.Text,
  'category' : Type__1,
});
export const StudentId = IDL.Principal;
export const Type = IDL.Variant({
  'normal' : IDL.Null,
  'mild' : IDL.Null,
  'extremelySevere' : IDL.Null,
  'severe' : IDL.Null,
  'moderate' : IDL.Null,
});
export const DASS21Subscale = IDL.Record({
  'severity' : Type,
  'rawScore' : IDL.Nat,
});
export const Time = IDL.Int;
export const DASS21Assessment = IDL.Record({
  'id' : IDL.Nat,
  'stress' : DASS21Subscale,
  'anxiety' : DASS21Subscale,
  'studentId' : StudentId,
  'answers' : IDL.Vec(IDL.Nat),
  'timestamp' : Time,
  'depression' : DASS21Subscale,
});
export const TeacherId = IDL.Principal;
export const ParentId = IDL.Principal;
export const StudentExtProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'age' : IDL.Text,
  'fieldOfStudy' : IDL.Text,
  'wellnessGoal' : IDL.Text,
});
export const HabitSummary = IDL.Record({
  'sleepStreak' : IDL.Nat,
  'exerciseStreak' : IDL.Nat,
  'outdoorStreak' : IDL.Nat,
  'xp' : IDL.Nat,
  'lastUpdated' : IDL.Int,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addLanguageActivity' : IDL.Func(
      [IDL.Text, ActivityType, IDL.Text, IDL.Nat],
      [IDL.Nat],
      [],
    ),
  'addResource' : IDL.Func(
      [IDL.Text, ResourceCategory, IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
      [IDL.Nat],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createDASS21Assessment' : IDL.Func(
      [IDL.Vec(IDL.Nat), IDL.Vec(IDL.Nat)],
      [IDL.Nat],
      [],
    ),
  'createParentProfile' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'createStudentProfile' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'createTeacherProfile' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'getAllActivities' : IDL.Func([], [IDL.Vec(LanguageActivity)], ['query']),
  'getAllResources' : IDL.Func([], [IDL.Vec(WellnessResource)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getStudentAssessments' : IDL.Func(
      [StudentId],
      [IDL.Vec(DASS21Assessment)],
      ['query'],
    ),
  'getStudentExtendedProfile' : IDL.Func(
      [StudentId],
      [IDL.Opt(StudentExtProfile)],
      ['query'],
    ),
  'getHabitSummary' : IDL.Func(
      [StudentId],
      [IDL.Opt(HabitSummary)],
      ['query'],
    ),
  'getMoodHistory' : IDL.Func(
      [StudentId],
      [IDL.Text],
      ['query'],
    ),
  'getParentLinkedStudent' : IDL.Func(
      [],
      [IDL.Opt(IDL.Principal)],
      ['query'],
    ),
  'getTeacherStudents' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Text, IDL.Text))],
      ['query'],
    ),
  'getTeacherStudentsWithProfiles' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Text, IDL.Text, IDL.Opt(StudentExtProfile), IDL.Opt(HabitSummary)))],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'linkStudentToTeacherAndParent' : IDL.Func([TeacherId, ParentId], [], []),
  'saveStudentExtendedProfile' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'saveMoodEntry' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'saveHabitSummary' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat],
      [],
      [],
    ),
  'submitActivityResponse' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Nat], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ActivityType = IDL.Variant({
    'affirmation' : IDL.Null,
    'word_association' : IDL.Null,
    'journaling' : IDL.Null,
  });
  const ResourceCategory = IDL.Variant({
    'book' : IDL.Null,
    'article' : IDL.Null,
    'podcast' : IDL.Null,
    'activity' : IDL.Null,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Type__2 = IDL.Variant({
    'affirmation' : IDL.Null,
    'word_association' : IDL.Null,
    'journaling' : IDL.Null,
  });
  const LanguageActivity = IDL.Record({
    'id' : IDL.Nat,
    'difficultyLevel' : IDL.Nat,
    'title' : IDL.Text,
    'activityType' : Type__2,
    'prompt' : IDL.Text,
  });
  const Type__1 = IDL.Variant({
    'book' : IDL.Null,
    'article' : IDL.Null,
    'podcast' : IDL.Null,
    'activity' : IDL.Null,
  });
  const WellnessResource = IDL.Record({
    'id' : IDL.Nat,
    'url' : IDL.Text,
    'title' : IDL.Text,
    'tags' : IDL.Vec(IDL.Text),
    'description' : IDL.Text,
    'category' : Type__1,
  });
  const StudentId = IDL.Principal;
  const Type = IDL.Variant({
    'normal' : IDL.Null,
    'mild' : IDL.Null,
    'extremelySevere' : IDL.Null,
    'severe' : IDL.Null,
    'moderate' : IDL.Null,
  });
  const DASS21Subscale = IDL.Record({
    'severity' : Type,
    'rawScore' : IDL.Nat,
  });
  const Time = IDL.Int;
  const DASS21Assessment = IDL.Record({
    'id' : IDL.Nat,
    'stress' : DASS21Subscale,
    'anxiety' : DASS21Subscale,
    'studentId' : StudentId,
    'answers' : IDL.Vec(IDL.Nat),
    'timestamp' : Time,
    'depression' : DASS21Subscale,
  });
  const TeacherId = IDL.Principal;
  const ParentId = IDL.Principal;
  const StudentExtProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'age' : IDL.Text,
    'fieldOfStudy' : IDL.Text,
    'wellnessGoal' : IDL.Text,
  });
  const HabitSummary = IDL.Record({
    'sleepStreak' : IDL.Nat,
    'exerciseStreak' : IDL.Nat,
    'outdoorStreak' : IDL.Nat,
    'xp' : IDL.Nat,
    'lastUpdated' : IDL.Int,
  });

  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addLanguageActivity' : IDL.Func(
        [IDL.Text, ActivityType, IDL.Text, IDL.Nat],
        [IDL.Nat],
        [],
      ),
    'addResource' : IDL.Func(
        [IDL.Text, ResourceCategory, IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
        [IDL.Nat],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createDASS21Assessment' : IDL.Func(
        [IDL.Vec(IDL.Nat), IDL.Vec(IDL.Nat)],
        [IDL.Nat],
        [],
      ),
    'createParentProfile' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'createStudentProfile' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'createTeacherProfile' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'getAllActivities' : IDL.Func([], [IDL.Vec(LanguageActivity)], ['query']),
    'getAllResources' : IDL.Func([], [IDL.Vec(WellnessResource)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getStudentAssessments' : IDL.Func(
        [StudentId],
        [IDL.Vec(DASS21Assessment)],
        ['query'],
      ),
    'getStudentExtendedProfile' : IDL.Func(
        [StudentId],
        [IDL.Opt(StudentExtProfile)],
        ['query'],
      ),
    'getHabitSummary' : IDL.Func(
        [StudentId],
        [IDL.Opt(HabitSummary)],
        ['query'],
      ),
    'getMoodHistory' : IDL.Func(
        [StudentId],
        [IDL.Text],
        ['query'],
      ),
    'getParentLinkedStudent' : IDL.Func(
        [],
        [IDL.Opt(IDL.Principal)],
        ['query'],
      ),
    'getTeacherStudents' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Text, IDL.Text))],
        ['query'],
      ),
    'getTeacherStudentsWithProfiles' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Text, IDL.Text, IDL.Opt(StudentExtProfile), IDL.Opt(HabitSummary)))],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'linkStudentToTeacherAndParent' : IDL.Func([TeacherId, ParentId], [], []),
    'saveStudentExtendedProfile' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'saveMoodEntry' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'saveHabitSummary' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat],
        [],
        [],
      ),
    'submitActivityResponse' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Nat], []),
  });
};

export const init = ({ IDL }) => { return []; };
