/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ActivityType = { 'affirmation' : null } |
  { 'word_association' : null } |
  { 'journaling' : null };
export interface DASS21Assessment {
  'id' : bigint,
  'stress' : DASS21Subscale,
  'anxiety' : DASS21Subscale,
  'studentId' : StudentId,
  'answers' : Array<bigint>,
  'timestamp' : Time,
  'depression' : DASS21Subscale,
}
export interface DASS21Subscale { 'severity' : Type, 'rawScore' : bigint }
export interface LanguageActivity {
  'id' : bigint,
  'difficultyLevel' : bigint,
  'title' : string,
  'activityType' : Type__2,
  'prompt' : string,
}
export type ParentId = Principal;
export type ResourceCategory = { 'book' : null } |
  { 'article' : null } |
  { 'podcast' : null } |
  { 'activity' : null };
export type StudentId = Principal;
export type TeacherId = Principal;
export type Time = bigint;
export type Type = { 'normal' : null } |
  { 'mild' : null } |
  { 'extremelySevere' : null } |
  { 'severe' : null } |
  { 'moderate' : null };
export type Type__1 = { 'book' : null } |
  { 'article' : null } |
  { 'podcast' : null } |
  { 'activity' : null };
export type Type__2 = { 'affirmation' : null } |
  { 'word_association' : null } |
  { 'journaling' : null };
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface WellnessResource {
  'id' : bigint,
  'url' : string,
  'title' : string,
  'tags' : Array<string>,
  'description' : string,
  'category' : Type__1,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addLanguageActivity' : ActorMethod<
    [string, ActivityType, string, bigint],
    bigint
  >,
  'addResource' : ActorMethod<
    [string, ResourceCategory, string, string, Array<string>],
    bigint
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createDASS21Assessment' : ActorMethod<
    [Array<bigint>, Array<bigint>],
    bigint
  >,
  'createParentProfile' : ActorMethod<[string, string], undefined>,
  'createStudentProfile' : ActorMethod<[string, string], undefined>,
  'createTeacherProfile' : ActorMethod<[string, string], undefined>,
  'getAllActivities' : ActorMethod<[], Array<LanguageActivity>>,
  'getAllResources' : ActorMethod<[], Array<WellnessResource>>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getStudentAssessments' : ActorMethod<[StudentId], Array<DASS21Assessment>>,
  'getTeacherStudents' : ActorMethod<[], Array<[Principal, string, string]>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'linkStudentToTeacherAndParent' : ActorMethod<
    [TeacherId, ParentId],
    undefined
  >,
  'submitActivityResponse' : ActorMethod<[bigint, string], bigint>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];
