/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Time = bigint;
export type StudentId = Principal;
export type ParentId = Principal;
export type TeacherId = Principal;
export interface DASS21Assessment {
    id: bigint;
    stress: DASS21Subscale;
    anxiety: DASS21Subscale;
    studentId: StudentId;
    answers: Array<bigint>;
    timestamp: Time;
    depression: DASS21Subscale;
}
export interface LanguageActivity {
    id: bigint;
    difficultyLevel: bigint;
    title: string;
    activityType: Type__2;
    prompt: string;
}
export interface DASS21Subscale {
    severity: Type;
    rawScore: bigint;
}
export interface WellnessResource {
    id: bigint;
    url: string;
    title: string;
    tags: Array<string>;
    description: string;
    category: Type__1;
}
export enum ActivityType {
    affirmation = "affirmation",
    word_association = "word_association",
    journaling = "journaling"
}
export enum Type {
    normal = "normal",
    mild = "mild",
    extremelySevere = "extremelySevere",
    severe = "severe",
    moderate = "moderate"
}
export enum Type__1 {
    book = "book",
    article = "article",
    podcast = "podcast",
    activity = "activity"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addLanguageActivity(title: string, activityType: ActivityType, prompt: string, difficultyLevel: bigint): Promise<bigint>;
    addResource(title: string, category: ResourceCategory, description: string, url: string, tags: Array<string>): Promise<bigint>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createDASS21Assessment(answers: Array<bigint>, socialIsolationAnswers: Array<bigint>): Promise<bigint>;
    createParentProfile(name: string, email: string): Promise<void>;
    createStudentProfile(name: string, email: string): Promise<void>;
    createTeacherProfile(name: string, email: string): Promise<void>;
    getAllActivities(): Promise<Array<LanguageActivity>>;
    getAllResources(): Promise<Array<WellnessResource>>;
    getCallerUserRole(): Promise<UserRole>;
    getStudentAssessments(studentId: StudentId): Promise<Array<DASS21Assessment>>;
    isCallerAdmin(): Promise<boolean>;
    linkStudentToTeacherAndParent(teacherId: TeacherId, parentId: ParentId): Promise<void>;
    submitActivityResponse(activityId: bigint, response: string): Promise<bigint>;
}
import type { ActivityType as _ActivityType, DASS21Assessment as _DASS21Assessment, DASS21Subscale as _DASS21Subscale, LanguageActivity as _LanguageActivity, ResourceCategory as _ResourceCategory, StudentId as _StudentId, Time as _Time, Type as _Type, Type__1 as _Type__1, Type__2 as _Type__2, UserRole as _UserRole, WellnessResource as _WellnessResource } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addLanguageActivity(arg0: string, arg1: ActivityType, arg2: string, arg3: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addLanguageActivity(arg0, to_candid_ActivityType_n1(this._uploadFile, this._downloadFile, arg1), arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addLanguageActivity(arg0, to_candid_ActivityType_n1(this._uploadFile, this._downloadFile, arg1), arg2, arg3);
            return result;
        }
    }
    async addResource(arg0: string, arg1: ResourceCategory, arg2: string, arg3: string, arg4: Array<string>): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addResource(arg0, to_candid_ResourceCategory_n3(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addResource(arg0, to_candid_ResourceCategory_n3(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n5(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n5(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createDASS21Assessment(arg0: Array<bigint>, arg1: Array<bigint>): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createDASS21Assessment(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createDASS21Assessment(arg0, arg1);
            return result;
        }
    }
    async createParentProfile(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createParentProfile(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createParentProfile(arg0, arg1);
            return result;
        }
    }
    async createStudentProfile(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createStudentProfile(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createStudentProfile(arg0, arg1);
            return result;
        }
    }
    async createTeacherProfile(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createTeacherProfile(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTeacherProfile(arg0, arg1);
            return result;
        }
    }
    async getAllActivities(): Promise<Array<LanguageActivity>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllActivities();
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllActivities();
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllResources(): Promise<Array<WellnessResource>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllResources();
                return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllResources();
            return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStudentAssessments(arg0: StudentId): Promise<Array<DASS21Assessment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getStudentAssessments(arg0);
                return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStudentAssessments(arg0);
            return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async linkStudentToTeacherAndParent(arg0: TeacherId, arg1: ParentId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.linkStudentToTeacherAndParent(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.linkStudentToTeacherAndParent(arg0, arg1);
            return result;
        }
    }
    async submitActivityResponse(arg0: bigint, arg1: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.submitActivityResponse(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitActivityResponse(arg0, arg1);
            return result;
        }
    }
    async getTeacherStudents(): Promise<Array<[import("@icp-sdk/core/principal").Principal, string, string]>> {
        if (this.processError) {
            try {
                const result = await (this.actor as any).getTeacherStudents();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await (this.actor as any).getTeacherStudents();
            return result;
        }
    }
}
function from_candid_DASS21Assessment_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DASS21Assessment): DASS21Assessment {
    return from_candid_record_n21(_uploadFile, _downloadFile, value);
}
function from_candid_DASS21Subscale_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DASS21Subscale): DASS21Subscale {
    return from_candid_record_n23(_uploadFile, _downloadFile, value);
}
function from_candid_LanguageActivity_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LanguageActivity): LanguageActivity {
    return from_candid_record_n9(_uploadFile, _downloadFile, value);
}
function from_candid_Type__1_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Type__1): Type__1 {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_Type__2_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Type__2): Type__2 {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function from_candid_Type_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Type): Type {
    return from_candid_variant_n25(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function from_candid_WellnessResource_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WellnessResource): WellnessResource {
    return from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    url: string;
    title: string;
    tags: Array<string>;
    description: string;
    category: _Type__1;
}): {
    id: bigint;
    url: string;
    title: string;
    tags: Array<string>;
    description: string;
    category: Type__1;
} {
    return {
        id: value.id,
        url: value.url,
        title: value.title,
        tags: value.tags,
        description: value.description,
        category: from_candid_Type__1_n15(_uploadFile, _downloadFile, value.category)
    };
}
function from_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    stress: _DASS21Subscale;
    anxiety: _DASS21Subscale;
    studentId: _StudentId;
    answers: Array<bigint>;
    timestamp: _Time;
    depression: _DASS21Subscale;
}): {
    id: bigint;
    stress: DASS21Subscale;
    anxiety: DASS21Subscale;
    studentId: StudentId;
    answers: Array<bigint>;
    timestamp: Time;
    depression: DASS21Subscale;
} {
    return {
        id: value.id,
        stress: from_candid_DASS21Subscale_n22(_uploadFile, _downloadFile, value.stress),
        anxiety: from_candid_DASS21Subscale_n22(_uploadFile, _downloadFile, value.anxiety),
        studentId: value.studentId,
        answers: value.answers,
        timestamp: value.timestamp,
        depression: from_candid_DASS21Subscale_n22(_uploadFile, _downloadFile, value.depression)
    };
}
function from_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    severity: _Type;
    rawScore: bigint;
}): {
    severity: Type;
    rawScore: bigint;
} {
    return {
        severity: from_candid_Type_n24(_uploadFile, _downloadFile, value.severity),
        rawScore: value.rawScore
    };
}
function from_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    difficultyLevel: bigint;
    title: string;
    activityType: _Type__2;
    prompt: string;
}): {
    id: bigint;
    difficultyLevel: bigint;
    title: string;
    activityType: Type__2;
    prompt: string;
} {
    return {
        id: value.id,
        difficultyLevel: value.difficultyLevel,
        title: value.title,
        activityType: from_candid_Type__2_n10(_uploadFile, _downloadFile, value.activityType),
        prompt: value.prompt
    };
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    affirmation: null;
} | {
    word_association: null;
} | {
    journaling: null;
}): ActivityType {
    return "affirmation" in value ? ActivityType.affirmation : "word_association" in value ? ActivityType.word_association : "journaling" in value ? ActivityType.journaling : value;
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    book: null;
} | {
    article: null;
} | {
    podcast: null;
} | {
    activity: null;
}): Type__1 {
    return "book" in value ? Type__1.book : "article" in value ? Type__1.article : "podcast" in value ? Type__1.podcast : "activity" in value ? Type__1.activity : value;
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    normal: null;
} | {
    mild: null;
} | {
    extremelySevere: null;
} | {
    severe: null;
} | {
    moderate: null;
}): Type {
    return "normal" in value ? Type.normal : "mild" in value ? Type.mild : "extremelySevere" in value ? Type.extremelySevere : "severe" in value ? Type.severe : "moderate" in value ? Type.moderate : value;
}
function from_candid_vec_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_WellnessResource>): Array<WellnessResource> {
    return value.map((x)=>from_candid_WellnessResource_n13(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_DASS21Assessment>): Array<DASS21Assessment> {
    return value.map((x)=>from_candid_DASS21Assessment_n20(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_LanguageActivity>): Array<LanguageActivity> {
    return value.map((x)=>from_candid_LanguageActivity_n8(_uploadFile, _downloadFile, x));
}
function to_candid_ActivityType_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ActivityType): _ActivityType {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_ResourceCategory_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ResourceCategory): _ResourceCategory {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ActivityType): {
    affirmation: null;
} | {
    word_association: null;
} | {
    journaling: null;
} {
    return value == ActivityType.affirmation ? {
        affirmation: null
    } : value == ActivityType.word_association ? {
        word_association: null
    } : value == ActivityType.journaling ? {
        journaling: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Type__1): {
    book: null;
} | {
    article: null;
} | {
    podcast: null;
} | {
    activity: null;
} {
    return value == Type__1.book ? {
        book: null
    } : value == Type__1.article ? {
        article: null
    } : value == Type__1.podcast ? {
        podcast: null
    } : value == Type__1.activity ? {
        activity: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
